spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/user
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: flyway_history