spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/user
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: flyway_history

user:
  config:
    password:
      min-length: 10
      max-length: 64
      require-uppercase: false
      require-special: false
      allowed-special-chars: "#?!@$%^&*-]"
      bcrypt-strength: 10
      bcrypt-version: $2A
    account:
      retention-months:
        marked-for-removal: 2
        idle: 24
